name: .NET Core Application Test Workflow

on:
  push:
    branches:
      - main
  
  workflow_dispatch:
  
jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:

    - name: Set up Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: 20
        
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore dependencies and build the solution
    - name: Restore and build solution
      run: dotnet build --configuration ${{ matrix.configuration }}

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3

    # Run tests for the solution
    - name: Run unit tests
      run: dotnet test --configuration ${{ matrix.configuration }}
